[package]
name = "txn_lock"
version = "0.6.0"
authors = ["code@tinychain.net"]
edition = "2021"
description = "A futures-aware transactional read-write lock"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/haydnv/tinychain.git"

keywords = ["transaction", "transactional", "lock", "version"]
categories = ["concurrency", "data-structures"]

[features]
logging = ["log"]

[dependencies]
tokio = { version = "1.24", features = ["sync"] }
log = { version = "0.4", features = ["release_max_level_info"], optional = true }

[dev-dependencies]
futures = "0.3"
