[package]
name = "txn_lock"
version = "0.1.0"
authors = ["haydn@tinychain.net"]
edition = "2021"
description = "A futures-aware transactional read-write lock"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/haydnv/tinychain.git"

keywords = ["transaction", "transactional", "lock", "version"]
categories = ["concurrency", "data-structures"]

[dependencies]
